### ISSUE TITLE
Question with deployment

### ISSUE THREAD

**Issue by luchua-bc** [alokkusingh/saml#2]
Hi @alokkusingh ,

This is a very nice project. I have been trying to find an SAML2 SP in Java and yours meets my needs exactly. 

However, I cannot find documentation on how to deploy the generated sp-1.0-SNAPSHOT.jar and idp-1.0-SNAPSHOT.jar to a web container. Would you please add the documentation on how to run them on an application server like Tomcat?

Thanks,
@luchua-bc

**Comment by alokkusingh** [comment]
Hi @luchua-bc,

Sorry for the late response and thanks for liking this project!

You may change the packaging to "war" and exclude the Tomcat from the dependency list (optional) - this should work.

Regards,
Alok
